### ISSUE TITLE
[Feature request] BB calculation according to EMA1/EMA2 coin settings 

### ISSUE THREAD

**Issue by MrG4dget** [Sjakil/gunthy-gui#11]
I'm not sure how the BB is currently calculated, but it seems to me, as if it is a hard coded value. Would be awesome if it would recalculate BB according to the coin settings.

Furthermore it would be realy helpful to display the buy/sell threshold as a graph...
So when the trategy is set to BB 20/20, you would see the buy limit (green line) and the sell limit (red line).
![image](https://user-images.githubusercontent.com/3408565/29761522-be115e2a-8bc9-11e7-854c-8adb85afd943.png)

In my opinion this would make adjusting and tweaking the parameters much easier!

Keep up the good work!

**Comment by Sjakil** [comment]
As of version 1.1 the GUI allows you to configure bollinger SMA and SD values. I hope this is good enough :)
