### ISSUE TITLE
Targets & Error not getting buy and sell

### ISSUE THREAD

**Issue by mattquickenden** [Sjakil/gunthy-gui#13]
![image](https://user-images.githubusercontent.com/6086602/30170497-1f914426-93a4-11e7-8bb5-b559540fc109.png)
The bot seems to be connected/authenticated okay and getting data, however, the buy and sell never displays and therefore the graph never shows the targets either.  I'm using gunbot 4.0.5 Any thoughts?

**Comment by Sjakil** [comment]
Admittedly, this is not documented properly, but in order for the gunbot targets to work, the gunbot has to have it's "VERBOSE" mode enabled. You can find this in the gunbot configuration (bottomleft button below red/green circular button labelled G up top). Please let me know if it works after that.

**Comment by mattquickenden** [comment]
I did actually just figure this out trying to debug bb in 5.0.1. Verbose worked. Ps.  Gui works with 5.0.1 but there are some errors with bb calculations I think. Gunthar had added some additional statistics to 5.0.1 a SMA and stddev to the bollandger band. Any chance they are coming to the Gui?

**Comment by mattquickenden** [comment]
I have gone back to 3.3.5 due to suspect buys, it doesnt look like 3.3.5 has a verbose mode.  Can you confirm the buy / sell line is only for the later versions?
