### ISSUE TITLE
0.992 - Sort by Balance not working

### ISSUE THREAD

**Issue by CultureCrypto** [Sjakil/gunthy-gui#26]
I'll admit that I'm not sure what the intended functionality is, whether by altcoin balance count, or by BTC value, but neither seem to be the result.  I can invert the sort, and I get a different sort that way too!  In other words, if I point the sort arrow down, the pair on the bottom is not the same as if I point the arrow up, and get the first pair.

![image](https://user-images.githubusercontent.com/30902036/30823818-7c6d8866-a1fb-11e7-9e66-cf273039aefb.png)

**Comment by Sjakil** [comment]
The only thing it indicates is whether or not you have balances. Because of this, it doesnt sort on the actual amount you have.

**Comment by CultureCrypto** [comment]
Ok - thank you! Closing.
