### ISSUE TITLE
latest version missing "gui" folder

### ISSUE THREAD

**Issue by utdrmac** [Sjakil/gunthy-gui#3]
Just downloaded gunthy-gui-macos-0.95.zip and there's no "gui" folder; only a binary. https://github.com/Sjakil/gunthy-gui/wiki/Installation page doesn't say anything other than to extract and run.

**Comment by utdrmac** [comment]
gunthy-gui-linux-0.95.zip appears to have all necessary files

**Comment by Sjakil** [comment]
That would be a silly mistake on my part. I re-uploaded the gunthy-gui-macos-0.95.zip file. Thank you for letting me know.
