### ISSUE TITLE
TImestamp on graph view shows time of local computer, not server. Should show server time.  

### ISSUE THREAD

**Issue by brandrew0** [Sjakil/gunthy-gui#37]
![screenshot 2017-10-08 21 18 24](https://user-images.githubusercontent.com/32626132/31323551-f3e4d192-ac6e-11e7-8d01-9c032bc57b1c.png)
see screenshot. This is taken from my laptop in CST, though my server is UTC. These dots line up fine when viewing in a browser on my server, but are off when viewing from a URL on another machine.

**Comment by Sjakil** [comment]
Hi Brandrew,

Version 1.1 of the GUI adds an option to configure an offset for the trades displayed on the chart. This should allow you to correct for this problem.
