### ISSUE TITLE
Balance coin name in USDT & ETH shows BTC

### ISSUE THREAD

**Issue by Dangerous-Mind** [Sjakil/gunthy-gui#38]
Message shows Balance in BTC but this is the USDT-XMR trade
The same thing happens to the ETH-XMT

![image](https://user-images.githubusercontent.com/31196073/31359511-31f40d62-ad42-11e7-9233-0b66701cf703.png)

**Comment by Sjakil** [comment]
This should be fixed in version 1.1 :)
