### ISSUE TITLE
[Enhancement - v1.0 ] Have pages and/or tabs to divide multiple instances

### ISSUE THREAD

**Issue by caogeoge** [Sjakil/gunthy-gui#41]
Hi Sjakil,

Thank you for the multiple instances of Gunthy GUI in v1.0. It was a great feature that we really need.

I have another request for multiple instances management. Currently lots of us are using our phones to access Gunthy GUI. With the current multiple instances, if I run 20 instances with 10 pairs per instance (for a total of 200 pairs), all of these 200 pairs are shown on one page of Gunthy GUI.

The problem with this is when you access Gunthy GUI on your smartphone, the browser will surely hangs since smartphone browsers can't handle much JavaScript. Thus, if we can have a way to divide the views of this 200 pairs onto 20 pages and/or tabs, that would be great since the mobile web browser can load 10 pairs much more easily than 200 pairs and it won't hang.

We can probably provide an option for displaying 1 instance per page or all instances in one page. Along with this, the "Search" bar would still search through all instances.

Thank you Sjakil for the feature.

**Comment by Sjakil** [comment]
Hi Caogeoge!

As of version 1.1 the GUI supports pagination with an adjustible number of pairs per page. By default, it sets it to 10 on touch devices and to 50 and any other device. This should improve the performance on mobile devices.
