### ISSUE TITLE
New Log

### ISSUE THREAD

**Issue by ghost** [Sjakil/gunthy-gui#44]
With the last update the gunbot log output was replaced with websocket events. 

You have to click on the events to see details like SMA, BBs, and whether the bot has bought/sold. This is really annoying, especially when the log is moving. I know I can pause the log, but is was far easier before to see at a glance what the bot was doing. 

Is there any way to enable the log again like it was before?

**Comment by Sjakil** [comment]
The log output from before will most likely never come back. I did however just upload version 1.1 of the GUI and it shows much more information. Therefore I consider this issue closed.
