### ISSUE TITLE
Timezone isse with v0.97 

### ISSUE THREAD

**Issue by MrG4dget** [Sjakil/gunthy-gui#9]
- Running v0.97 with gunbot V4.0.5
- Win10 
 
Somehow the GUI seems to be in the wrong timezone, as it is 2h behind.
Gunbot logs show correct time, but all GUI related logs are -2h offset. 

Any idea how to fix it?

**Comment by MrG4dget** [comment]
Solved by manually setting timezone to UTC and adjusting the time.

**Comment by MrG4dget** [comment]
I think there is still an issue with the time settings. Timestamp in the logs are correct, but somehow the graph is off...
![image](https://user-images.githubusercontent.com/3408565/29792426-a916ef4a-8c40-11e7-94f3-1a4e53606e20.png)

Any ideas how to fix or where to look? Furthermore you see, that I can only switch between 5min and 10min view...

**Comment by Sjakil** [comment]
This issue should (finally) be resolved in version 1.1. You can use timezone offsets to configure the candlesticks and trades
